version: "3"
services:
  reverseproxy:
      image: amitgoswami1027/udagram-goswami-reverseproxy
      ports:
              - "0.0.0.0:8080:8080"
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: amitgoswami1027/udagram-goswami-userapi
    volumes:
            - $HOME/.aws:/root/.aws
    env_file: 
         - .env  
  backend-feed:
    image: amitgoswami1027/udagram-goswami-feedapiv2
    volumes:
           - $HOME/.aws:/root/.aws
    env_file:
           - .env
  frontend:
    image: amitgoswami1027/udagram-goswami-ionicfrontendv2
    ports:
            - "8100:80"
