version: "3"
services:
  reverseproxy:
      image: amitgoswami1027/udagram-goswami-reverseproxy
      ports:
              - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: amitgoswami1027/udagram-goswami-userapi
    volumes:
      - /root/.aws
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DB: ${POSTGRESS_DB}
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_BUCKET: ${AWS_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://0.0.0.0:8080"
  backend-feed:
    image: amitgoswami1027/udagram-goswami-feedapi
    volumes:
      - /root/.aws
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DB: ${POSTGRESS_DB} 
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_BUCKET: ${AWS_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://0.0.0.0:8080"
  frontend:
    image: amitgoswami1027/udagram-goswami-ionicfrontend
    ports:
            - "0.0.0.0:8100:80"
